### ISSUE TITLE
Consistent name for player index

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#10]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/resolvers/player-resolver.ts#L14

In the player table, we have several unique index : id, index, vttl_index so I've been surprised that I had to use yet another name for the argument.

As already suggested in #7 and #8, we should only expose one index and name it the same way everywhere.  In TabT SOAP, I used "unique_index".

**Comment by Fllorent0D** [comment]
Renamed in 4b8d722f3917e561ed54b18f438584f78ea4ff71
