### ISSUE TITLE
Query players on club

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#12]
I'm not yet very familiar with GraphQL so there's probably another way to achieve the same goal.

But to build players list, my first idea would be to query the ```players``` on club, as an example:

```graphql
query {
  players(club: 'WVL129'){
  	unique_index,
        first_name,
  	last_name,
  }
}
```

**Comment by Fllorent0D** [comment]
A way to query players in a club is by passing by the club resolver. `members` could be renamed into players to be more readable 
```gql
{
  club(clubId: "WVL129"){
      members{
         last_name
    }
  }
}`

**Comment by Fllorent0D** [comment]
and the parameter `clubId` must be rename also

**Comment by gfrenoy** [comment]
Shouldn't it be "clubs" (with a "s") ?

**Comment by gfrenoy** [comment]
Tried the following:

```graphql
query {
  club(clubId:"WVL129"){
    short_name,
    name,
    members{
      unique_index,
      first_name,
      last_name
    }
  }
}
```

but it fails:

```
Cannot read property 'club_id' of null
```

**Comment by Fllorent0D** [comment]
There was a issue in a dataloader. Normally with latest changes in should be better

**Comment by gfrenoy** [comment]
Works indeed better, thanks !

But it looks like it does not select the club correctly ; the player list is empty:

```json
{
  "data": {
    "club": {
      "short_name": "Heuvelland",
      "name": "T.T.C. Heuvelland",
      "members": []
    }
  }
}
```

And the club name is not correct ; I selected season 19 for which the name should be "T.T.C. Ieper-Heuvelland".

WVL129 is a tricky one ; it has been renamed a few times already :-/

So you can have several rows for the same indice in the ```clubs``` table ; not sure how to have this in the resolver / dataloader but in SQL ; you have to do something like this to select the right club:

```sql
SET @CURRENT_SEASON = 19;
SELECT
	*
FROM
	clubs
WHERE 1
	AND indice = 'WVL129'
	AND IFNULL(first_season, 0) <= @CURRENT_SEASON
	AND IFNULL(last_season, @CURRENT_SEASON) >= @CURRENT_SEASON;
```

**Comment by Fllorent0D** [comment]
I was not aware of this. I will change this to load the appropriate one

**Comment by Fllorent0D** [comment]
I adapted the loader to load only club with the requested season 8764804d1f1c0c6d1980589f63fb7c392fbd0a82. It should be even better than previously :p

**Comment by gfrenoy** [comment]
Perfect :)  Thanks.
