### ISSUE TITLE
Active status

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#15]
Tried the following:

```graphql
query {
  players(unique_index: 505290) {
    unique_index,
    first_name,
    last_name,
    status
  }
}
```

The status field is returned as "null" but should be "A" (active).

Maybe the logic is flaw but this is the way it works today : if a player is not listed in table ```playerstatus```, you are active.

Note that to be fully complete, we should also check that the player is a member of a club ; otherwise it should not be marked as active.

**Comment by Fllorent0D** [comment]
Was not aware of the logic. Fixed a9da070e849216c9021f2e4d7c6fcfbe14c923e5
