### ISSUE TITLE
player vs players / club vs clubs ?

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#16]
Was wondering why you have ```players``` (with a "s") to extract players:

```graphql
query {
  players(unique_index: 505290) {
    unique_index,
    first_name,
    last_name,
    status
  }
}
```

But ```club``` (without a "s") for clubs:

```graphql
query {
  club(clubId:"WVL129"){
    short_name,
    name
  }
}
```

Is there are any reason ?  Shouldn't we try to be consistent ?

**Comment by Fllorent0D** [comment]
Yep it's not consistant. The main reason is that the '...s' function returns an array and the singular an object.
I will only keep the non-plural one to load only 1 club or 1 player at a time for now.

**Comment by Fllorent0D** [comment]
Changed in 08bd10f83a86a99fd7c7bf5865cda4721e141572
