### ISSUE TITLE
Typo in TournamentRegularityRankings.ts

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#4]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/entities/TournamentRegularityRankings.ts#L21

Should be ```regularityRanking``` (with capital "R").

**Comment by Fllorent0D** [comment]
Fixed in 5e7475a08448b8d682b1689b094d8bec50abed0f
