### ISSUE TITLE
No federation name in field names

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#5]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/entities/PlayerInfo.ts#L103

I would suggest to avoid using the name of a particular federation in any of the field name.

In TabT SOAP, I called this field ```unique_index```.

**Comment by Fllorent0D** [comment]
Field renamed in 04a533d

**Comment by gfrenoy** [comment]
Field is still referenced in PlayerInfo.ts and player-resolver.ts ...

**Comment by Fllorent0D** [comment]
My bad went too fast 23fe82d
