### ISSUE TITLE
Email must be a private field

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#6]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/entities/PlayerInfo.ts#L62

Field ```email``` and ```emailcc``` cannot be public and require at least an admin access.

**Comment by Fllorent0D** [comment]
Marked both fields with the`@Authorized()` decorator so you need admin rights to access them

**Comment by Fllorent0D** [comment]
25591be
