### ISSUE TITLE
Internal ID should be hidden

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#7]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/entities/PlayerInfo.ts#L37

The real "key" of this table is the "unique_index" (aka vttl_index) ; the internal ID should remain hidden.

**Comment by Fllorent0D** [comment]
Changed 50712b68e1231822c20b419052def50aefa10e70. Internal key is hidden and `unique_index ` is returned as ID
