### ISSUE TITLE
Obsolete index to be hidden

### ISSUE THREAD

**Issue by gfrenoy** [Fllorent0D/Tabt-GraphQL#8]
https://github.com/Fllorent0D/Tabt-GraphQL/blob/6a171ed880fb856084dff9ef25408a33ce14ba7e/src/entities/PlayerInfo.ts#L94

This is a "legacy" index that is not used anymore and that must be hidden.

**Comment by Fllorent0D** [comment]
Removed in 50712b68e1231822c20b419052def50aefa10e70
